name: Deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
      - name: Build with Gradle
        run: ./gradlew buildRelease
      - uses: actions/upload-artifact@v2
        with:
          name: mdi-android
          path: mdi-android/lib-mdi-android/build/outputs/aar/*
