name: Deploy release

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy_lib:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Publish package
        run: ./gradlew assembleRelease publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build sample app
        run: ./gradlew sample:packageReleaseUniversalApk
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: sample-release
          path: sample/build/outputs/universal_apk/release/*.apk

  create_release:
    runs-on: ubuntu-latest
    needs: build_sample
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/download-artifact@v2
        with:
          name: sample-release
      - name: Upload sample app apk
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sample-release-universal-unsigned.apk
          asset_name: sample-release-universal-unsigned.apk
          asset_content_type: application/vnd.android.package-archive