name: Build sample app

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      run: ./gradlew sample:packageReleaseUniversalApk
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: sample-release
        path: sample/build/outputs/universal_apk/release/sample-release-universal-unsigned.apk
